### ISSUE TITLE
Export fish path 

### ISSUE THREAD

**Issue by avo12ck** [mooch443/trex#153]
**Is your feature request related to a problem? Please describe.**
I am trying to track some fish which Trex is great at but the head and tail orientation swaps a lot which is not good because I need a direction vector for the fish. I

**Describe the solution you'd like**
 I noticed that the "path" line I see on the GUI is pretty accurate and was wondering if I could directly export the coordinates/ tangent line of the path I am seeing.

**Describe alternatives you've considered**
I have tried multiple combination of parameters but my fish is transparent so still has some error.

**Additional context**
<img width="163" alt="Screen Shot 2022-06-04 at 12 19 43 PM" src="https://user-images.githubusercontent.com/106881236/172016573-2d10bd54-11e8-4350-882c-ab7deb92e0bc.png">

Also as I side note, how do I do manual matching for the fish? sometimes they swap identities after they collide but I have yet to figure out how to use the manual match feature. Thank you!

**Comment by mooch443** [comment]
Hey! Real-time data will obviously never be perfect, but transparent fish are certainly difficult. As always with these kinds of issues, example videos and exact logs of what you did are super helpful!

From what I can tell here it should be working OK, but it seems the eyes would probably sometimes be part of the individual/not be part of the individual? This happens a lot with these kinds of transparent species. Usually one can reduce the threshold enough to merge them again, but I haven't seen your videos yet I think - so potentially it's a bit harder here. There are ways to close holes in objects during covnersion (-use_closing), so you could use a track_threshold of 0 during tracking and only set a threshold during conversion.

Regarding the manual matching, have a look at this page I just added: https://trex.run/docs/gui.html#manually-assigning-individuals 

Hope this helps :-)
