### ISSUE TITLE
Fail on building tgrabs when building from source

### ISSUE THREAD

**Issue by elhananby** [mooch443/trex#16]
Hi Tristan, thanks for the great work on this project! I recently got a new workstation and tried to build TRex again, but got an error.

When building TRex from source on Ubuntu 18.04 with Basler support, the build fails on `Linking CXX executable ../../tgrabs
`. 

The full error is:
`/home/benyishay_la/anaconda3/envs/tracking/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /opt/pylon/lib/libpylonutility.so: undefined reference to clock_gettime@GLIBC_2.17'`
`/home/benyishay_la/anaconda3/envs/tracking/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /opt/pylon/lib/libpylonbase.so: undefined reference to memcpy@GLIBC_2.14'`
`collect2: error: ld returned 1 exit status`
`src/grabber/CMakeFiles/tgrabs.dir/build.make:294: recipe for target 'tgrabs' failed`
`make[2]: *** [tgrabs] Error 1`
`CMakeFiles/Makefile2:747: recipe for target 'src/grabber/CMakeFiles/tgrabs.dir/all' failed`
`make[1]: *** [src/grabber/CMakeFiles/tgrabs.dir/all] Error 2`
`Makefile:159: recipe for target 'all' failed`
`make: *** [all] Error 2`

I hope it's okay I didn't use the exact report format.

Best,
Elhanan

**Comment by mooch443** [comment]
Hey, thank you for your report!

I think I will need some more clarification in this case:
- How are you trying to build it? Is this using the conda build recipe, or did you follow the pure manual install instructions?
- What does the environment look like that you build in?
- Also, can you attach the full build log? You can append them to your post here.

Thanks!

**Comment by elhananby** [comment]
Hi Tristan,
1) I am using the pure manual install instructions.
2) I am using a conda virtual environment initialized using:
`conda create -n tracking -c conda-forge cmake ffmpeg tensorflow-gpu=2 cxx-compiler c-compiler glfw mesa-libgl-devel-cos6-x86_64 libxdamage-devel-cos6-x86_64 libxi-devel-cos6-x86_64 libxxf86vm-cos6-x86_64 libselinux-devel-cos6-x86_64 libuuid-devel-cos6-x86_64 mesa-libgl-devel-cos6-x86_64`
3) see attached.

Also, a few other points:
- I am using Pylon 6, which requires me to change the pylon lib location in `/trex/Application/src/commons/CMakeModules`, from `/opt/pylon5/lib64\32` to `/opt/pylon/lib`, as well as `/opt/pylon5/include` to `/opt/pylon/include`.
- I also tried compiling it with pylon5 but then I get another error, see attached log.
- During compiling I am getting this error:
`make[4]: warning: jobserver unavailable: using 
[trex_build_output_pylon6.txt](https://github.com/mooch443/trex/files/6079702/trex_build_output_pylon6.txt)
-j1.  Add '+' to parent make rule.`
Which I guess means the compiler isn't using all the available threads/core? I don't know enough about C/MAKE to solve this myself, and it's not a big issue either way.
[trex_build_output_pylon5.txt](https://github.com/mooch443/trex/files/6079701/trex_build_output_pylon5.txt)


Thanks,
Elhanan

**Comment by mooch443** [comment]
Hey,

Firstly, thank you for your detailed information. Potentially pylon5 works better -- to me it seems like somehow Pylon6 might have been compiled with a different std lib. At least the error looks very weird. I am using pylon5.0.12 at least, so I know that this works on Debian. You might have to adapt the script in CMakeModules for your specific library names, which is annoying but they call them differently in each version.

PYLON_GEN2_LIBRARY and PYLON_GEN_LIBRARY are missing, so their names need to be added. What do `ls /opt/pylon*` and `ls /opt/pylon*/lib*` say on your system? I can add the proper names in my dev version then.

Regarding the jobserver: It is indeed a warning only, something OpenCV related. Nothing to worry about for now!

Thanks for your report!
-Tristan

**Comment by elhananby** [comment]
Hi,
the output from `ls /opt/pylon*` is:
```bin  include  INSTALL  lib64  README  ReleaseNotes.txt  Samples  setup-usb.sh  share```
from `ls /opt/pylon*/lib*` is:
```
gentlproducer
libbxapi-5.1.0.so
libbxapi.so
libFirmwareUpdate_gcc_v3_1_Basler_pylon_v5_1.so
libGCBase_gcc_v3_1_Basler_pylon_v5_1.so
libGenApi_gcc_v3_1_Basler_pylon_v5_1.so
libgxapi-5.1.0.so
libgxapi.so
liblog4cpp_gcc_v3_1_Basler_pylon_v5_1.so
libLog_gcc_v3_1_Basler_pylon_v5_1.so
libMathParser_gcc_v3_1_Basler_pylon_v5_1.so
libNodeMapData_gcc_v3_1_Basler_pylon_v5_1.so
libpylonbase-5.1.0.so
libpylonbase.so
libpylonc-5.1.0.so
libpylonc.so
libpylon_TL_bcon-5.1.0.so
libpylon_TL_bcon.so
libpylon_TL_camemu-5.1.0.so
libpylon_TL_camemu.so
libpylon_TL_gige-5.1.0.so
libpylon_TL_gige.so
libpylon_TL_usb-5.1.0.so
libpylon_TL_usb.so
libpylonutility-5.1.0.so
libpylonutility.so
libuxapi-5.1.0.so
libuxapi.so
libXmlParser_gcc_v3_1_Basler_pylon_v5_1.so
pylon-libusb-1.0.so
```

Thanks
Elhanan

**Comment by mooch443** [comment]
Thank you! I added these into my  [CMakeModules extension](https://github.com/mooch443/trex/blob/c5f3f6b3279d46911fe18e246b9426871ceaf482/Application/src/commons/CMakeModules/FindBaslerPylon.cmake#L31). You can replace this file in your version and check if it works. If it does *not* work, I suggest you try downloading Pylon 5.0 instead of 5.1, if they still have it available on their website. It seems indeed like a weird error, and probably something very specific. I am really hoping we can find out what the issue is here.
