### ISSUE TITLE
Proximity Issue

### ISSUE THREAD

**Issue by Toshea111** [mooch443/trex#181]
**Describe the bug**
While tracking termites, I am experiencing a frequent issue with individuals merging into a single blob when in close proximity. After consulting the FAQs, I have tried altering the 'blob_split' parameters, detection thresholds, and TGrabs thresholds to no avail, and 'manual_splits' is only sometimes successful. Is there a way that this can be avoided, to ensure that identity is maintained in such cases?

**To Reproduce**
Attached is an example video showing the issue.

**Expected behavior (if it is not a simple crash)**

**Screenshots**
See attached video.

**Computer (please complete the following information):**
 - Operating system: Windows 10
 - Build hash: 4ce4be1cd1679bcca4da5af8780dd86c1d31050b
 - Terminal used: PowerShell

**Additional context**
Merging appears to be most common when individuals are side-by-side.

https://user-images.githubusercontent.com/109351104/184354183-4bbe1071-a6f3-4977-924d-60f1510b3eab.mp4

**Comment by mooch443** [comment]
Hey, sorry for the late response - I would suggest altering the `blob_size_ranges` to more closely fit the individual sizes. Also `track_max_speed` could be relevant. If both are set to good values, the individuals should be split. You can also try to set `track_decay = 1`, which I always do for termites. You can look these up in the docs as well :-)
