### ISSUE TITLE
Error in Local conda channel Installation

### ISSUE THREAD

**Issue by mariaioan** [mooch443/trex#183]
Hello! 

I want to use live-tracking, and I'm trying to compile the software. I tried both suggested ways and I'm having errors with both.

I have downloaded Visual Studio, and in Anaconda Powershell as admin  [in Windows 10] , when I run ./build_conda_package.bat, I get this error: 

```
CMake Error:
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.



-- USER environment variable is set to:
CMake Error at CMakeLists.txt:8 (project):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.



-- Configuring incomplete, errors occurred!
See also "C:/ProgramData/Anaconda3/conda-bld/trex_1664291194034/work/Application/build/CMakeFiles/CMakeOutput.log".
CMake Error:
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.

```

I have followed the instructions from this post and it didn't fix it.  
https://stackoverflow.com/questions/51668676/cmake-visual-studio-15-2017-could-not-find-any-instance-of-visual-studio
![error_visual_studio](https://user-images.githubusercontent.com/95088939/192568787-b4ebc7b4-7dbc-4041-8836-0d298cb9813c.png)

**Comment by mooch443** [comment]
This would be resolved by installing Visual Studio 2019 :-)
