### ISSUE TITLE
Size of GUI 

### ISSUE THREAD

**Issue by mi2celis** [mooch443/trex#192]
This is not a bug per say. 
When the GUI window starts, the window is tiny. At first I kept missing it. Is there a way to specify the size of the GUI window when it is deployed?

I am running on Ubuntu 20.04 and installed the TRex pre-built binaries using Anaconda.

Thank you

**Comment by mooch443** [comment]
Hey, thanks for reporting this - may I ask what the resolution of your video is? If it is really small, I can imagine this happening. And does it say v1.1.9 in the window title?

**Comment by mi2celis** [comment]
Video is 1536x768

V1.1.9 does appear in the window title.

Thank you for looking into this

Maria Celis

**Comment by mooch443** [comment]
Very funky indeed - I have not been able to reproduce this anywhere yet unfortunately. Instead, I have set a minimum window size to the project. So at least it shouldn't be too small to see now. Or with the next release, that is. :-) Thanks for reporting!
