### ISSUE TITLE
File format for visual fields

### ISSUE THREAD

**Issue by CassGitHub** [mooch443/trex#194]
Hello, 
I would like to use visual field data however I find it difficult to extract them. Could you help me with that please? For instance I have seen that the npz file contains "depth", "eye_pos", "eye_angle" and more, however I don't know how to extract those data as a normal dataframe such as a csv format, and I don't understand to what it refers as there can be much more line than the number of frame in my video or much more columns it seems for depth for instance while it give it only for one fish ? 
Have you released any documentation regarding this file, because I haven't found it ? 
Furthermore, I am just wondering why the visual field is not directly added to the output csv or npz file ? Because it is requiring several steps to try to get those data, to what I understood I have for each object of my video to click on each of them before to click in the menu tab to then choose to save the visual field. Maybe there is an easier way to do it ?  
And could you give me some clue on how to open easily such npz file to have it as a dataframe to anlayse ? 
Thanks a lot for your help. Because this software is really good with manual correction availale etc. and such other measurements would be really useful for the purpose of my research but I would be glad to use fully all the possibilities. 
Best wishes

**Comment by CassGitHub** [comment]
Hello, 
I would like to use visual field data however I find it difficult to extract them. Could you help me with that please? For instance I have seen that the npz file contains "depth", "eye_pos", "eye_angle" and more, however I don't know how to extract those data as a normal dataframe such as a csv format, and I don't understand to what it refers as there can be much more line than the number of frame in my video or much more columns it seems for depth for instance while it give it only for one fish ? 
Have you released any documentation regarding this file, because I haven't found it ? 
Furthermore, I am just wondering why the visual field is not directly added to the output csv or npz file ? Because it is requiring several steps to try to get those data, to what I understood I have for each object of my video to click on each of them before to click in the menu tab to then choose to save the visual field. Maybe there is an easier way to do it ?  
And could you give me some clue on how to open easily such npz file to have it as a dataframe to anlayse ? 
Thanks a lot for your help. Because this software is really good with manual correction availale etc. and such other measurements would be really useful for the purpose of my research but I would be glad to use fully all the possibilities. 
Best wishes

**Comment by mooch443** [comment]
Have a look here https://github.com/mooch443/trex/issues/95 and here https://trex.run/docs/formats.html#visual-fields - does that help?
