### ISSUE TITLE
Training images not being saved

### ISSUE THREAD

**Issue by mi2celis** [mooch443/trex#196]
**Describe the bug**
Using trex for tracking a video.
I am using auto_train and trying to save the training images by using
recognition_save_training_images = true
Training completes successfully, however, the training images are not being saved.

My settings for trex are as follows:
```
blob_size_ranges = [[0.0170333,3.089644]]
track_threshold = 15
track_max_individuals = 10
track_max_speed = 200
output_posture_data=true
auto_train = true
recognition_image_scale = 0.75
recognition_image_size = [256,256]
recognition_save_training_images = true
```

and the command I use is
```
trex \
    -d ${EWD}/results/${BASE} \
    -i ${EWD}/videos_pv/${BASE}.pv \
    -s ${PARAMS} \
    -log_file track_${BASE}.log
```
where EWD, BASE and PARAMS are defined.
All other results are being saved to ${EWD}/results/${BASE}.

TRex is running on Ubuntu 20.04.4 LTS. Have 
NVIDIA Corporation TU106M [GeForce RTX 2070 Mobile] / Mesa Intel® UHD Graphics 630 (CFL GT2)
TRex v1.1.9

Log file from trex session is attached
[output.txt](https://github.com/mooch443/trex/files/11125480/output.txt)

**Comment by mooch443** [comment]
So, looking at your log, have you checked`"/home/mimi/data/lab/trex/experiments/EXP_20211208153624//results/20211208-153646___G_pZMafXy___F_008___D_001___A_180___O_500___S_700/20211208-153646___G_pZMafXy___F_008___D_001___A_180___O_500___S_700_L_validation_data.npz"`?
