### ISSUE TITLE
TRex crash

### ISSUE THREAD

**Issue by jessamis1** [mooch443/trex#197]
Hi, when trying to open trex after using tgrabs it is crashing. I am using MacOS and have included tensorflow. I get this message on my terminal 
FATAL: Segmentation Fault. Logged StackTrace
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process
Panic 

I also get a crash report which I can include if needed. Any help on this would be much appreciated!

**Comment by mooch443** [comment]
Hey, yes that would help. What do you mean you "included" tensorflow?

**Comment by jessamis1** [comment]
Hi sorry, by that I mean I have installed it onto my conda tracking environment as recommended on the installation page. I get the issue when I open the video on trex however interestingly it seems to have just resolved itself!!

**Comment by mooch443** [comment]
Great! So we can consider this solved then :-)
