### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by elhananby** [mooch443/trex#2]
Hi Tristan,
I'm trying to compile trex on my system (Ubuntu 18.04.5, gcc-8, g++-8) since I am using Basler cameras, and the build fails for some reason that is unclear to me. I've attached the terminal output after running `trex_build_unix.sh`. The main issue seems to be with building `glfw`.

Thanks,
Elhanan
[trex_build_201020.txt](https://github.com/mooch443/trex/files/5409040/trex_build_201020.txt)

**Comment by mooch443** [comment]
Hey there, thanks for trying it out.

Which version of Pylon are you using? It does not seem to find the libraries, which is odd.
And you are right about GLFW. As it is stating at the end, it does not find the Xrandr dev package. You can either install them using conda, or simply do it system-wide (apt-get) -- does not usually harm you. Not sure how you would install that on Ubuntu, but I'm sure Google will know. If you wish to use conda for that, here are a couple ones you can install on linux (conda-forge required):
https://anaconda.org/conda-forge/libxrandr-devel-cos6-x86_64 (or also without the devel if it doesnt suffice)
Same for other libraries that might come up (-cos6... are the libraries specifically for your system)
https://anaconda.org/search?q=xcursor

**Comment by elhananby** [comment]
Hi Tristan - yep, doing `sudo apt-get install xorg-dev libglu1-mesa-dev` solved that issue.

However, now I have issues with it not detecting the Pylon installation:
`[ 85%] Linking CXX executable ../../../trex_check_python`
`/usr/bin/ld: cannot find -lPYLONBASE_LIBRARY-NOTFOUND`
`/usr/bin/ld: cannot find -lPYLON_UTILITY_LIBRARY-NOTFOUND`
`/usr/bin/ld: cannot find -lPYLON_GEN_LIBRARY-NOTFOUND`
`/usr/bin/ld: cannot find -lPYLON_GEN2_LIBRARY-NOTFOUND`
`/usr/bin/ld: cannot find -luuid`
`collect2: error: ld returned 1 exit status`
`src/tracker/python/CMakeFiles/trex_check_python.dir/build.make:152: recipe for target 'trex_check_python' failed`
`make[2]: *** [trex_check_python] Error 1`
`CMakeFiles/Makefile2:942: recipe for target 'src/tracker/python/CMakeFiles/trex_check_python.dir/all' failed`
`make[1]: *** [src/tracker/python/CMakeFiles/trex_check_python.dir/all] Error 2`
`Makefile:159: recipe for target 'all' failed`
`make: *** [all] Error 2`

I currently have installed Pylon version `6.1.1`. I also tried uninstalling it and reinstalling version `5.2.0` (as you tested it according to the documentation), and then the error is slightly different:

`[ 84%] Linking CXX executable ../../../trex_check_python`
`/usr/bin/ld: cannot find -lPYLON_GEN_LIBRARY-NOTFOUND`
`/usr/bin/ld: cannot find -lPYLON_GEN2_LIBRARY-NOTFOUND`
`/usr/bin/ld: cannot find -luuid`
`collect2: error: ld returned 1 exit status`
`src/tracker/python/CMakeFiles/trex_check_python.dir/build.make:154: recipe for target 'trex_check_python' failed`
`make[2]: *** [trex_check_python] Error 1`
`CMakeFiles/Makefile2:942: recipe for target 'src/tracker/python/CMakeFiles/trex_check_python.dir/all' failed`
`make[1]: *** [src/tracker/python/CMakeFiles/trex_check_python.dir/all] Error 2`
`Makefile:159: recipe for target 'all' failed`
`make: *** [all] Error 2`

Thanks,
Elhanan

**Comment by mooch443** [comment]
Whats your output for `ls /opt/pylon5/lib64`? I assume I am missing some library names in the `Application/src/commons/CMakeModules/FindBaslerPylon.cmake`. I can add those easily.

It's also still missing libuuid-dev apparently.

**Comment by elhananby** [comment]
I've installed libuuid-dev with `sudo apt install uuid-dev`.

The output of `ls /opt/pylon5/lib64` is attached..
[ls_pylon5.txt](https://github.com/mooch443/trex/files/5409532/ls_pylon5.txt)

**Comment by mooch443** [comment]
Alright, you may try pulling the newest version using `git pull` from the master branch and see if it finds your libraries now!

**Comment by elhananby** [comment]
I'll have to check it tomorrow and will keep you updated.
Thank you for all the quick help!

**Comment by mooch443** [comment]
No worries! You can edit the file yourself, too, in case it does not work. It's pretty straight-forward (just add more names to the existing lists of names).

**Comment by elhananby** [comment]
Hi Tristan, I just had time to check it again today, but it seems everything's working now.
Thanks for all the help!
