### ISSUE TITLE
Example settings file

### ISSUE THREAD

**Issue by uday-chockanathan** [mooch443/trex#20]
Hi Tristan,

Thank you for creating this software, putting it out there for others to use, and supporting open science. I've been applying TRex to some mouse videos I have. I was wondering if you could post an example of a .settings file? I would like to create one, but I don't know what the formatting should be (I should mention that I am pretty new to python - my main language is MATLAB, so please forgive me for not being able to reverse-engineer this answer!)

If you will allow me one more unrelated request - could you please post the TGrabs/TRex parameters you used to generate those amazing mouse tracking results in Appendix 12/Figure A1? 

Appreciate your help!
Uday

**Comment by mooch443** [comment]
Hey!

Thanks for your interest in our software :-)

Settings files are simple text files with a `parameter = value` syntax (one per line). You can look up parameters at https://trex.run/docs/parameters_trex.html for example. Almost anything found there can be set using either the command-line or a settings file. Settings files have to be either (1) named with the same basename as the .PV video file you want to associate with them, or (2) declared when starting TRex (command-line) using `-s /path/to/settings.settings`.

You can find results/settings files at https://videos.trex.run, where you'll have to download the V1+V2_Appendix12_results.zip file. Here is what's inside 4Mice.settings (also an example of a settings file):

```
blob_size_ranges = [[2,7]]
gui_auto_scale_focus_one = false
gui_focus_group = [0,3]
gui_show_dataset = true
gui_show_posture = false
individual_prefix = "mouse"
midline_invert = true
recognition_image_scale = 0.75
recognition_image_size = [128,128]
recognition_save_training_images = true
recognition_segment_add_factor = 1.15
track_max_individuals = 4
track_max_reassign_time = 0.25
track_max_speed = 100
track_posture_threshold = 150
track_speed_decay = 1
track_threshold = 135
```

Conversion of the videos has been performed (in the case of 4Mice) with the following command-line:
```
tgrabs -i 4Mice.mp4 -threshold 80
```

Hope this helps!
-Tristan

**Comment by uday-chockanathan** [comment]
Hey Tristan, thanks for your help!
