### ISSUE TITLE
Unable to convert video file with tgrabs

### ISSUE THREAD

**Issue by janey-haddock** [mooch443/trex#211]
I compiled Trex to my laptop to use for my thesis project, but I am unable to convert video files using tgrabs.

We tried converting the file from a .MP4 to MOV. We tried converting different, unrelated videos. We tried it on a different system altogether, but we keep getting the same error. I have attached what we are seeing to a .txt file. 

[trex_error.txt](https://github.com/mooch443/trex/files/12851891/trex_error.txt)

**Comment by mooch443** [comment]
Ah I see, you have a manual compile (on Windows). You may have to go to the build folder -> x64 -> bin -> something -> opencv_*ffmpeg.dll and copy this file into your Release folder. It's hidden somewhere in the build folder after a successful build. Unfortunately, this step is still not automated for manual builds - and honestly it's kind of annoying that OpenCV does this.

**Comment by mooch443** [comment]
Ah, for me it was this path:

trex\Application\build\opencv_install\x64\vc17\bin\opencv_videoio_ffmpeg481_64.dll

**Comment by janey-haddock** [comment]
Thank you so much! 

I ended up trying it with a normal install and it worked. But I will keep this in mind if I ever dare to try a manual compile again.
