### ISSUE TITLE
TRex fails to launch on MacOS after installation

### ISSUE THREAD

**Issue by givitelli** [mooch443/trex#217]
**Describe the bug**
Hi! I am trying to use TRex on a MacOS Ventura 13.5 with Apple M1 Chip. Everything seems to install successfully (I followed install directions for MacOS using miniforge). However,  when I activate my tracking environment and go to launch trex or tgrabs, I get an error 'dyld[4960]: missing symbol called' and an apple problem report window opens up saying 'TRex quit unexpectedly'. 
I installed the beta version using the installer, through the beta environment I was able to open the GUI for trgrabs/trex and open a video to track, but when I went to track the video the GUI would again quit unexpectedly. I'd like to not use the beta version so I want to focus on trying to get the normal install to launch. I tried updating trex which did not work. ChatGPT told me to reinstall gnutls package and check that the value of the DYLD_LIBRARY_PATH environment variable was not set, I did both of those and the error did not resolve.

**To Reproduce**
1. Install trex using provided installation instructions for MacOS, Apple Silicone. 
2. In terminal, 'conda activate tracking' to open tracking environment
3. in tracking environment, 'trex' or 'tgrabs' to launch or 'trex -i videoname -s' to open a video
4. Launch fails for both, same error for both

If possible, please also include the full terminal output as a file attachment.

terminal output: Last login: Thu Jan 18 13:39:48 on ttys000
(base) ablab@SOMHGE-AB-iMac1 ~ % conda activate tracking
(tracking) ablab@SOMHGE-AB-iMac1 ~ % trex
Using conda prefix '/Users/ablab/miniforge3/envs/tracking/bin/'.
Calling '/Users/ablab/miniforge3/envs/tracking/bin/TRex.app/Contents/MacOS/TRex'...
dyld[4960]: missing symbol called

Apple Problem Report: 
[problem_report.txt](https://github.com/mooch443/trex/files/13980699/problem_report.txt)

**Expected behavior (if it is not a simple crash)**
With normal installation, I expected trex or tgrabs to launch.

**Computer (please complete the following information):**
 - Operating system: MacOS Ventura 13.5
 - Build hash : md5
 - Terminal used: Mac Terminal

Thank you so much !!

**Comment by mooch443** [comment]
Hey! I can only see that there's something going on with ffmpeg and loading symbols. Maybe some conda repository was updated with a different ffmpeg version than the software supports?

Could you provide the ``conda list`` of your environment? In any case, there'll be a new beta out soon which will hopefully not be as brittle :)

**Comment by mooch443** [comment]
Just got back from field-work ... :) 
Oh, I am sorry. You are using Ventura 13.5? I think this may be the issue. Although it is difficult for me to find out which exact function is triggering the incompatibility - I only have machines with macOS 14 and above... Does this also happen if you start the program with
```
trex -i video.pv -nowindow
```
? That would at least narrow it down to "opening a window and rendering graphics into it.

Although this is a very weird thing since I am compiling all Mac versions for >=11.0 and would expect the compiler to throw an error if I am using newer features. Hm. Does the beta version work?

```
conda create -n beta_test --override-channels -c trex-beta -c pytorch -c conda-forge trex
```

and then try running it
```
trex
```

Thanks for checking and your patience! :)

**Comment by givitelli** [comment]
Hi! Thanks for your response, here's the results of these suggestions: 

**You are using Ventura 13.5?** 
Yes, I am. 

**Does this also happen if you start the program with**
> trex -i video.pv -nowindow
Yes, it still happens when I try this. 

**Does the beta version work?**
I did try the beta version previously (I used the installer provided in the docs), and was able to get the GUI open but for some reason the GUI would crash when I tried to track videos. However, trying it now with the code you provided, the beta test version works!

I'll just use this beta version moving forward. Thanks so much for your help!

**Comment by mooch443** [comment]
You should probably update that version every now and again and switch to main channel once I push it. Just to be sure that things are working as intended - there used to be some bugs in some version related to the data output, so be careful. Right now at least I don't know of any. Cheers!
