### ISSUE TITLE
Beta: Doesn't run on command `trex`

### ISSUE THREAD

**Issue by roaldarbol** [mooch443/trex#226]
**Describe the bug**
Having installed the beta on MacOS with `conda`, I can't open trex - it seems something is missing.

**To Reproduce**
```command
(beta) ➜  trex-beta trex          
dyld[6477]: Library not loaded: @rpath/libopenh264.5.dylib
  Referenced from: <7326869B-2204-305F-815C-D52E20CC79EE> /Users/roaldarbol/mambaforge/envs/beta/lib/libavcodec.58.91.100.dylib
  Reason: tried: '/Users/roaldarbol/mambaforge/envs/beta/lib/libopenh264.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/roaldarbol/mambaforge/envs/beta/lib/libopenh264.5.dylib' (no such file), '/Users/roaldarbol/mambaforge/envs/beta/lib/libopenh264.5.dylib' (no such file), '/Users/roaldarbol/mambaforge/envs/beta/bin/../lib/libopenh264.5.dylib' (no such file), '/Users/roaldarbol/mambaforge/envs/beta/bin/../lib/libopenh264.5.dylib' (no such file), '/usr/local/lib/libopenh264.5.dylib' (no such file), '/usr/lib/libopenh264.5.dylib' (no such file, not in dyld cache)
[1]    6477 abort      trex
```

**Expected behavior (if it is not a simple crash)**
Expecting the application to open.

**Additional context**
On MacOS. 
I also tried with `trexa` (as that appears in the docs), but that seems to have been phased out already.

**Comment by mooch443** [comment]
can you provide your conda list? works for me, and openh264                  2.1.1 is installed. seems to me like you have the wrong combination of channels.

**Comment by roaldarbol** [comment]
My bad, the ARM64 threw me off - I thought that was the Intel, not M1/M2. So installing with 
```zsh
conda create -n beta --override-channels -c trex-beta -c pytorch -c defaults trex
```
works!
