### ISSUE TITLE
Averaging mode 'mode' does not work in TRex preview

### ISSUE THREAD

**Issue by mooch443** [mooch443/trex#25]

**Comment by roaldarbol** [comment]
Hi Tristan, I actually think this is the same thing I was encountering in #22 - tried yesterday, and worked fine with mean, min and max, but mode crashed it.

**Comment by mooch443** [comment]
> Hi Tristan, I actually think this is the same thing I was encountering in #22 - tried yesterday, and worked fine with mean, min and max, but mode crashed it.

Thanks for the heads-up, I hope it'll be fixed in v1.1.2 - now that I changed the underlying methods.
