### ISSUE TITLE
error in easy installation on windows

### ISSUE THREAD

**Issue by nurav375** [mooch443/trex#3]
I got the following error while attempting easy installation on windows 10, through anaconda 1.9:

LinkError: post-link script failed for package trexing::trex-1.0.2-saur
location of failed script: D:\*\anaconda\envs\tracking\Scripts\.trex-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:
stderr:
return code: 1

()

**Comment by mooch443** [comment]
Hey! Does this happen every time, even if you manually delete the environment folder before installation? I can't reproduce this here with the same config.

**Comment by nurav375** [comment]
yes, even after deleting the environment folder before every installation
attempt. I tried on two different systems (with the same config) and I got
the same error.

Then I also tried manual installation via conda channel.
In this method, after initial steps, when I execute following command:

conda create -n tracking -c local trex

the system is again unable to find the package and I get this error:

PackagesNotFoundError: The following packages are not available from
current channels:

  - trex

Current channels:

  - file:///D:/MyFiles/anaconda/conda-bld/win-64
  - file:///D:/MyFiles/anaconda/conda-bld/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

**Comment by mooch443** [comment]
Thanks for your response. You can try to get the 1.0.3 version from Anaconda (that I just uploaded) and see if removing these scripts fixes it. It's weird since these scripts were empty anyway, hm.

And your local install failed since the previous step apparently did not work. There was no package built, it seems.

**Comment by nurav375** [comment]
Hi,
I was able to install the version 1.0.3 using easy install and make it work.
Thanks for your help.

**Comment by mooch443** [comment]
Glad we could make it work!
