### ISSUE TITLE
error in trex/Application/src/commons/common/video/GenericVideo.cpp

### ISSUE THREAD

**Issue by fritzfrancisco** [mooch443/trex#4]
calibration error in trex/Application/src/commons/common/video/GenericVideo.cpp line 20:

if(map1.cols == disp.cols && map1.rows == disp.cols && map2.cols == disp.cols && map2.rows == disp.rows)

should be:

if(map1.cols == disp.cols && map1.rows == disp.rows && map2.cols == disp.cols && map2.rows == disp.rows)

**Comment by mooch443** [comment]
Yeah, was gonna mention I fixed it for next release :)

**Comment by fritzfrancisco** [comment]
Saw it! Great, already using gl2 😂
