### ISSUE TITLE
No OCL devices available.

### ISSUE THREAD

**Issue by StefanMPopp** [mooch443/trex#54]
When I start any tGrabs session I get the following exception message multiple times:
`No OCL devices available. Please check your graphics drivers and point the PATH variable to the appropriate folders.`
tGrabs still runs through, but it gets killed half the time and I want to exclude this issue as the cause of the killings.

Are you able to provide some additional information? Specifically, where the PATH variable can be found and what 'appropriate' means. Or just by what the issue is caused?

I work on Ubuntu 20.04 with an NVIDIA GPU and supposedly the latest drivers.

Thanks for any pointers you can give me!

**Comment by mooch443** [comment]
OpenCL drivers need to be loaded, which usually works as long as the NVIDIA drivers are also loaded. According to the internet, you may also (for Ubuntu) have to install something like the package ocl-icd-libopencl1 system-wide.

You may then also need to adjust the PATH variable. The PATH variable is (on Unix as well as Windows systems) an environment variable that is part of the system. You can set it directly in the terminal, or in your .bashrc file - how to set it and to which value, specifically on your system, I do not know. On my system, for example, I did not have to do anything extra!

**Comment by StefanMPopp** [comment]
Thanks, that cleared it up. I was not sure where this error was coming from.
