### ISSUE TITLE
support for matroska videos

### ISSUE THREAD

**Issue by astraw** [mooch443/trex#6]
**Describe the solution you'd like**
We have a lot of videos saved in .mkv containers (vp8, vp9 and h264 codecs). The [Matroska (MKV) format](https://en.wikipedia.org/wiki/Matroska) is a free, open-standard container format. It would be great if TGrabs could support reading .mkv videos like it supports reading .mp4 videos.

**Describe alternatives you've considered**
I have considered converting my videos using ffmpeg. For example:

`ffmpeg -i FILENAME.mkv -vcodec copy FILENAME.mp4`

will do the conversion without re-encoding the video. This would not be necessary if TGrabs would directly support MKV videos.

**Additional context**

**Comment by astraw** [comment]
Here is the error I get when I tried with an MKV video:

```
[EXCEPTION 14:37:05 main.cpp:783] Utils exception: Unknown extension 'mkv' for file 'FILENAME.mkv'.
Didn't clean up FrameGrabber properly.
```

**Comment by mooch443** [comment]
Thank you for reporting this issue! I completely glanced over MKV containers for some reason. I uploaded a new version to Anaconda just now, in which MKV files will be accepted and passed on to FFMPEG. 

If you're using the Anaconda version, you could create the environment in the same way again to get a clean install, or just update TRex in that environment. 

Feel free to re-open this issue if it does not work for you.

**Comment by astraw** [comment]
Great, that works. Thanks for the speedy update.
