### ISSUE TITLE
How to specify additional parameters to TGrabs.

### ISSUE THREAD

**Issue by astraw** [mooch443/trex#7]
The documentation at https://trex.run/docs/run.html mentions that I can specify additional parameters to TGrabs at the command line. However, how to do this is not specified. Could you update the docs to have a brief example of setting one or two parameters? Thanks!

**Comment by mooch443** [comment]
Hey, thank you for mentioning that! There was indeed no specific example in there. I updated it now, let me know if this fixes it for you!

**Comment by astraw** [comment]
thanks, that looks good. I haven't tested it but I assume it works.
