### ISSUE TITLE
Definitions of positional data variables

### ISSUE THREAD

**Issue by jptumulty** [mooch443/trex#83]
Hi, this is a great tool, thanks so much for developing and maintaining it!

I'm wondering if there is somewhere I can find definitions and units of all of the default variables associated with positional data. The tables on this page (https://trex.run/docs/formats.html) provide some, but not all. I can guess what some probably mean but I want to make sure. 

For example, I am wondering what "ANGLE" means. Also, some variables have "#pcentroid" after them, how does this differ from "#wcentroid"?

One issue I have with tracking is sometimes the midline and head position are off (or completely swapped in orientation from head to tail) for a few frames and but then go back to the correct position. I was hoping I could filter out these frames later if there is a variable that would indicate that the orientation of the head with respect to the centroid changed too fast, or reversed. 

Thanks!

**Comment by mooch443** [comment]
Hey!

I have now updated the docs page that you mentioned at https://trex.run/docs/formats.html#positional-data - hopefully this helps! There is a note on there that tries to explain the #pcentroid thing. Let me know if that's understandable.

Depending on the quality/difficulty of the video, outlines and midlines will be slightly off. You can usually improve your results with a few tricks. Just to highlight the most important parameters to look into:

- [outline_curvature_range_ratio](https://trex.run/docs/parameters_trex.html#outline_curvature_range_ratio): This impacts the tail-finding algorithm. If you increase this number (lets say switching from 0.03 to 0.07), the program would search for "larger" peeks, that are likely less "pointy", and the other way around.
- [outline_resample](https://trex.run/docs/parameters_trex.html#outline_resample): Changes the resolution of the outline. Smaller values produce more outline points (distance from one to the next point).
- [outline_approximate](https://trex.run/docs/parameters_trex.html#outline_approximate): Approximates the outline shape - higher values increase accuracy, but maybe also noise.
- [outline_smooth_samples](https://trex.run/docs/parameters_trex.html#outline_smooth_samples): Smoothes the outline before approximating it (usually does not do that much).

These interfere with each other of course. You may also want to adjust midline_resolution, if you feel like your individual is too big for just 12 points. 

-Tristan

**Comment by jptumulty** [comment]
This is great, thanks for the info and updating the definitions!
