### ISSUE TITLE
Documentation: -nowindow also works with TGrabs

### ISSUE THREAD

**Issue by roaldarbol** [mooch443/trex#89]
Just a quick note for the documentation: the `-nowindow` option is only described as a TRex parameter, but I was happy to realise it also works with TGrabs, so it will be worthwhile including it there as well. Especially as it allows the user to make use of cluster computing, which can be SUPER useful for bigger tracking projects. :-D

**Comment by mooch443** [comment]
Hey, thanks for the note! I didn't realize it wasn't advertised there too. The docs are automatically generated. I assume this was one of those historic things that I never adjusted... But yea, that is exactly why it was included :-) Closing for now, but feel free to let me know if you find other stuff like this!
