### ISSUE TITLE
Unable to output tracklet images

### ISSUE THREAD

**Issue by sccampbell02** [mooch443/trex#96]
Hello! I'd like to export normalized tracklet images of each animal in a video using the sample code provided in the documentation:
`trex -i C:\Users\sccampbell\TRex\dyad_demo.pv -output_image_per_tracklet true -tracklet_max_images 0 -auto_quit -auto_no_results -auto_no_tracking_data -tracklet_normalize_orientation true -output_dir C:\Users\sccampbell\TRex `

If I run the above code, TRex quits midway through generating the tracklet images without exporting anything at all. If I analyze half the video, this outputs only a summary 'tracklet_images.npz' file where both the 'images' and 'meta' matrices are empty. I see a nonzero number of segments for this video in the gui, so I'm not sure why this file would be empty. 
I've also replicated this issue with other videos - clips shorter than ~1min tend to output the empty .npz file while anything much longer results in a crash.

[Full terminal output for crash](https://github.com/mooch443/trex/files/8090807/full_video_tracklet.log)
[Full terminal output for empty .npz file](https://github.com/mooch443/trex/files/8090811/half_video_tracklet.log)

Computer:
- Operating System: Windows 10
- Trex 1.1.6
- Terminal used: Anaconda Prompt

Thanks for your work on this very helpful resource! Happy to provide more information if you need it.

**Comment by mooch443** [comment]
Hey, thanks for your report! So there is a print-out triggered, and something internally seems to go wrong. I haven't been able to reproduce this so far - if you are able to submit a minimal example, that would be really helpful (.pv/.settings file). I will keep looking into this, this should probably not happen. Question: did you track the video and THEN change thresholds, or other settings?

**Comment by mooch443** [comment]
Hey, I've updated the software. I did also a couple of days ago, but had to retract that version. Now hopefully everything works fine. See if an update helps you - I also mailed you some details back.
Cheers!

**Comment by sccampbell02** [comment]
Yep, I can now export tracklets with the update! Thanks very much for your help.
